name: examen-workflow

on:
  push:
    branches:
      - nueva-caracteristica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Tests
        run: pytest test.py

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: latest
          push: false  # No es necesario subir la imagen a un registro
