name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the action to execute'
        required: true
        default: 'main'  # Opción predeterminada, puedes cambiarla

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0-alpha.2

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest test.py

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
